export const ZipCode = [
    { id: 6033, municipality: "Alcantara" },
    { id: 6023, municipality: "Alcoy" },
    { id: 6030, municipality: "Alegria" },
    { id: 6040, municipality: "Aloguinsan" },
    { id: 6021, municipality: "Argao" },
    { id: 6042, municipality: "Asturias" },
    { id: 6031, municipality: "Badian" },
    { id: 6041, municipality: "Balamban" },
    { id: 6042, municipality: "Bantayan" },
    { id: 6036, municipality: "Barile" },
    { id: 6010, municipality: "Bogo" },
    { id: 6024, municipality: "Boljoon" },
    { id: 6008, municipality: "Borbon" },
    { id: 6019, municipality: "Carcar" },
    { id: 6005, municipality: "Carmen" },
    { id: 6006, municipality: "Catmon" },
    { id: 6000, municipality: "Cebu City" },
    { id: 6003, municipality: "Compostela" },
    { id: 6001, municipality: "Consolacion" },
    { id: 6017, municipality: "Cordova" },
    { id: 6013, municipality: "Daang-Bantayan" },
    { id: 6022, municipality: "Dalaguete" },
    { id: 6004, municipality: "Danao" },
    { id: 6035, municipality: "Dumanjug" },
    { id: 6026, municipality: "Ginatilan" },
    { id: 6015, municipality: "Lapu-Lapu City" },
    { id: 6002, municipality: "Liloan" },
    { id: 6016, municipality: "Mactan Airport" },
    { id: 6053, municipality: "Madridejos" },
    { id: 6029, municipality: "Malabuyoc" },
    { id: 6014, municipality: "Mandaue City" },
    { id: 6012, municipality: "Medellin" },
    { id: 6046, municipality: "Minglanilla" },
    { id: 6032, municipality: "Moalboal" },
    { id: 6037, municipality: "Naga" },
    { id: 6025, municipality: "Oslob" },
    { id: 6048, municipality: "Pilar" },
    { id: 6039, municipality: "Pinamungahan" },
    { id: 6049, municipality: "Poro" },
    { id: 6034, municipality: "Ronda" },
    { id: 6027, municipality: "Samboan" },
    { id: 6018, municipality: "San Fernando" },
    { id: 6050, municipality: "San Francisco" },
    { id: 6011, municipality: "San Remegio" },
    { id: 6047, municipality: "Santa Fe" },
    { id: 6026, municipality: "Santander" },
    { id: 6020, municipality: "Sibonga" },
    { id: 6007, municipality: "Sogod" },
    { id: 6009, municipality: "Tabogon" },
    { id: 6044, municipality: "Tabuelan" },
    { id: 6045, municipality: "Talisay" },
    { id: 6038, municipality: "Toledo City" },
    { id: 6043, municipality: "Tuburan" },
    { id: 6051, municipality: "Todela" },
];
